# Generated by Django 5.0.1 on 2024-01-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_published_date_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='searches',
        ),
    ]
