# Generated by Django 5.0.1 on 2024-01-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_country_news_country_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='country_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='searches',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
