# Generated by Django 5.0.1 on 2024-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_description_news_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='searches',
            field=models.IntegerField(default=0),
        ),
    ]
