# Generated by Django 5.0.1 on 2024-01-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_published_date_news_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='country',
            new_name='country_name',
        ),
    ]
