# Generated by Django 5.0.1 on 2024-01-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_country_news_country_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='news_country',
        ),
    ]
