# Generated by Django 5.0.1 on 2024-01-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_country_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
