# Generated by Django 5.0.1 on 2024-01-23 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='country_name',
            field=models.ForeignKey(db_column='country_name', on_delete=django.db.models.deletion.CASCADE, to='news.country'),
        ),
    ]
