# Generated by Django 5.0.1 on 2024-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
    ]
