# Generated by Django 5.0.1 on 2024-02-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_review',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='country_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
