# Generated by Django 5.0.1 on 2024-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_content_review_alter_news_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='country',
            table='news_country',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
