# Generated by Django 5.0.1 on 2024-02-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_country_name_alter_country_table_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['country_name'], name='news_country_34437b_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['searches'], name='news_searche_5460ef_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['date'], name='news_date_0a9db5_idx'),
        ),
    ]
